name: ci

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

env:
  # An envar that signals to tests we are executing in the CI environment
  CONTINUOUS_INTEGRATION: true
  # allow overriding Maven command
  MAVEN: ./mvnw --offline
  # maven.wagon.rto is in millis, defaults to 30m
  MAVEN_OPTS: "-Xmx512M -XX:+ExitOnOutOfMemoryError -Dmaven.wagon.rto=60000"
  MAVEN_INSTALL_OPTS: "-Xmx3G -XX:+ExitOnOutOfMemoryError -Dmaven.wagon.rto=60000"
  MAVEN_FAST_INSTALL: "-B --strict-checksums -V --quiet -T 1C -DskipTests -Dmaven.source.skip=true -Dair.check.skip-all"
  MAVEN_COMPILE_COMMITS: "-B --strict-checksums --quiet -T 1C -DskipTests -Dmaven.source.skip=true -Dair.check.skip-all=true -Dmaven.javadoc.skip=true --no-snapshot-updates --no-transfer-progress -pl '!:trino-server-rpm'"
  MAVEN_GIB: "-P gib -Dgib.referenceBranch=refs/remotes/origin/${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.event.repository.default_branch }}"
  MAVEN_TEST: "-B --strict-checksums -Dmaven.source.skip=true -Dair.check.skip-all --fail-at-end -P gib -Dgib.referenceBranch=refs/remotes/origin/${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.event.repository.default_branch }}"
  # Testcontainers kills image pulls if they don't make progress for > 30s and retries for 2m before failing. This means
  # that if an image doesn't download all it's layers within ~2m then any other concurrent pull will be killed because
  # the Docker daemon only downloads 3 layers concurrently which prevents the other pull from making any progress.
  # This value should be greater than the time taken for the longest image pull.
  TESTCONTAINERS_PULL_PAUSE_TIMEOUT: 600
  TESTCONTAINERS_SKIP_ARCHITECTURE_CHECK: true
  TEST_REPORT_RETENTION_DAYS: 5
  HEAP_DUMP_RETENTION_DAYS: 14
  # used by actions/cache to retry the download after this time: https://github.com/actions/cache/blob/main/workarounds.md#cache-segment-restore-timeout
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5

# Cancel previous PR builds.
concurrency:
  # Cancel all workflow runs except latest within a concurrency group. This is achieved by defining a concurrency group for the PR.
  # Non-PR builds have singleton concurrency groups.
  # When triggered by the repository_dispatch, add the expected SHA to avoid cancelling the run from the PR.
  group: |
    workflow=${{ github.workflow }},
    pr_number=${{ github.event_name == 'pull_request' && github.event.number || 'NA' }},
    dispatch_sha=${{ github.event_name == 'repository_dispatch' && github.event.client_payload.slash_command.args.named.sha || 'NA' }},
    commit_sha=${{ github.event_name != 'pull_request' && github.event_name != 'repository_dispatch' && github.sha || 'NA' }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 17
          - 19
          - 20
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # checkout all commits, as the build result depends on `git describe` equivalent
      - uses: ./.github/actions/setup
        with:
          java-version: ${{ matrix.java-version }}
      - name: Install
        run: |
          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
          $MAVEN clean install ${MAVEN_FAST_INSTALL} -pl ':trino-main' -am
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
      - name: Run
        run: $MAVEN test -Dair.check.skip-all=true -pl ':trino-main' -Dtest=TestObjectMapperConcur
